-- Supabase schema for the Ethical Zenith Hackers Intelligence Blog
-- Run this in Supabase SQL Editor.
-- The frontend uses the publishable key, so RLS is required.

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  number integer unique not null,
  title text not null,
  topic text not null,
  audience text,
  format text,
  keywords text,
  tags text,
  url text not null,
  created_at timestamptz not null default now()
);

alter table public.articles enable row level security;

drop policy if exists "Public can read published articles" on public.articles;
create policy "Public can read published articles"
on public.articles
for select
to anon
using (true);

create index if not exists articles_topic_idx on public.articles(topic);
create index if not exists articles_number_idx on public.articles(number);
